### ISSUE TITLE
Problem with installing Futura

### ISSUE THREAD

**Issue by sannawi** [pjamesjoyce/futura#4]
Hi!

I am trying to install Futura and I have gotten to the last step where the interface should be activated. However, I get this warning:

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
(base) C19OPUK:~ sannajo$ source activate futura
(futura) C19OPUK:~ sannajo$ futura_ui
futura      : **WARNING  Futura is using a monkeypatched version of Wurst
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.**

I have little experience in programming so I don't know what to do and would be grateful for some help!

Cheers,
Sanna

**Comment by pjamesjoyce** [comment]
The `futura_ui` command appears not to work correctly - this was meant to launch the ui as a separate entity so it wasn't blocking the console, but this functionality isn't vital. 
Just using `futura` as the launch command seems to work - I've changed the readme to suggest doing this instead.
